baseURL = "https://www.animalcarebg.com/"
languageCode = "en-us"
title = "Animal Care Center of Buffalo Grove"
googleAnalytics = "G-5B9MTSYBCL"
enableRobotsTXT = true
disableAliases = true
# post pagination
paginate = "6"
summaryLength = 30

#################### default parameters ################################

[params]
  logo = "images/animal-care-center-logo.png"
  disallowSearchEngines = true
  # Google Analitycs
  googleAnalytics = " " # Your ID# search 
  minifyBundles = true

# add redirects/headers
  [outputs]
  home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
  mediatype = "text/netlify"
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
  mediatype = "text/netlify"
  baseName = "_headers"
  isPlainText = true
  notAlternative = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[markup.goldmark.renderer]
  unsafe= true

[[menu.main]]
    name = "Services"
    url  = "/services/"
    weight = 2

  [[menu.main]]
    parent = "Services"
    name = "Wellness and Prevention"
    weight = 1
    url = "/services/wellness-and-prevention/"

  [[menu.main]]
    parent = "Services"
    name = "Laboratory"
    weight = 2
    url = "/services/laboratory/"

  [[menu.main]]
    parent = "Services"
    name = "Surgery"
    weight = 3
    url = "/services/surgery/"

  [[menu.main]]
    parent = "Services"
    name = "Dental Procedures"
    weight = 4
    url = "/services/dental-procedures/"

  [[menu.main]]
    parent = "Services"
    name = "Grooming"
    weight = 5
    url = "/services/grooming/"

  [[menu.main]]
    parent = "Services"
    name = "Emergency Services"
    weight = 6
    url = "/services/emergency-services/"

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 4

[[menu.main]]
    name = "Careers"
    url  = "/careers/"
    weight = 5

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 6
