backend:
  branch: main
  name: git-gateway
  repo: insight-creative/Animal-Care-Center

logo_url: https://animal-care-center.netlify.app/images/logo.png

media_folder: "static/images/blog" # Folder where user uploaded files should go
public_folder: "/blog"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    preview_path: "layouts/home.html"
    label: "Pages"
    media_folder: ""
    public_folder: ""
    editor:
      preview: false
    files:
      - file: "content/_index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "SEO",
              name: seo,
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: string },
                  { label: "Description", name: "description", widget: "text" },
                  {
                    label: "Featured Image",
                    name: "featured_image",
                    widget: image,
                  },
                ],
            }
          - {
              label: "Intro",
              name: intro,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Copy", name: "copy", widget: "text" },
                  { label: "Button Text", name: "button_text", widget: string },
                  { label: "Button Link", name: "button_link", widget: string },
                ],
            }
          - {
              label: "Services Block",
              name: services_block,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Copy", name: "copy", widget: "text" },
                  { label: "Button Text", name: "button_text", widget: string },
                  { label: "Button Link", name: "button_link", widget: string },
                  { label: "Image", name: "image", widget: "image" },
                  {
                    label: "Image Alternative Text",
                    name: "image_alt",
                    widget: string,
                  },
                ],
            }
          - {
              label: "About Block",
              name: about_block,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Copy", name: "copy", widget: "text" },
                  { label: "Button Text", name: "button_text", widget: string },
                  { label: "Button Link", name: "button_link", widget: string },
                  { label: "Image", name: "image", widget: "image" },
                  {
                    label: "Image Alternative Text",
                    name: "image_alt",
                    widget: string,
                  },
                ],
            }
      - file: "content/services/_index.md"
        label: "Services"
        name: "services"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "SEO",
              name: seo,
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: string },
                  { label: "Description", name: "description", widget: "text" },
                  {
                    label: "Featured Image",
                    name: "featured_image",
                    widget: image,
                  },
                ],
            }
          - {
              label: "Services Intro",
              name: services_intro,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Copy", name: "copy", widget: "text" },
                ],
            }
          - {
              label: "Services",
              name: "services",
              widget: "list",
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Copy", name: "copy", widget: "text" },
                  { label: "Button Text", name: "button_text", widget: string },
                  { label: "Button Link", name: "button_link", widget: string },
                ],
            }
      - file: "content/services/wellness-and-prevention/index.md"
        label: "Wellness and Prevention"
        name: "wellness-and-prevention"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "SEO",
              name: seo,
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: string },
                  { label: "Description", name: "description", widget: "text" },
                  {
                    label: "Featured Image",
                    name: "featured_image",
                    widget: image,
                  },
                ],
            }
          - {
              label: "Services Intro",
              name: services_intro,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Copy", name: "copy", widget: "text" },
                  {
                    label: "Service List",
                    name: "service_list",
                    widget: "list",
                    fields:
                      [{ label: "Service", name: "service", widget: string }],
                  },
                ],
            }
      - file: "content/services/laboratory/index.md"
        label: "Laboratory"
        name: "laboratory"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "SEO",
              name: seo,
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: string },
                  { label: "Description", name: "description", widget: "text" },
                  {
                    label: "Featured Image",
                    name: "featured_image",
                    widget: image,
                  },
                ],
            }
          - {
              label: "Services Intro",
              name: services_intro,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Copy", name: "copy", widget: "text" },
                  {
                    label: "Service List",
                    name: "service_list",
                    widget: "list",
                    fields:
                      [{ label: "Service", name: "service", widget: string }],
                  },
                ],
            }
      - file: "content/services/surgery/index.md"
        label: "Surgery"
        name: "surgery"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "SEO",
              name: seo,
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: string },
                  { label: "Description", name: "description", widget: "text" },
                  {
                    label: "Featured Image",
                    name: "featured_image",
                    widget: image,
                  },
                ],
            }
          - {
              label: "Services Intro",
              name: services_intro,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Copy", name: "copy", widget: "text" },
                  {
                    label: "Service List",
                    name: "service_list",
                    widget: "list",
                    fields:
                      [{ label: "Service", name: "service", widget: string }],
                  },
                ],
            }
      - file: "content/services/dental-procedures/index.md"
        label: "Dental Procedures"
        name: "dental-procedures"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "SEO",
              name: seo,
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: string },
                  { label: "Description", name: "description", widget: "text" },
                  {
                    label: "Featured Image",
                    name: "featured_image",
                    widget: image,
                  },
                ],
            }
          - {
              label: "Services Intro",
              name: services_intro,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Copy", name: "copy", widget: "text" },
                  {
                    label: "Service List",
                    name: "service_list",
                    widget: "list",
                    fields:
                      [{ label: "Service", name: "service", widget: string }],
                  },
                ],
            }
      - file: "content/services/grooming/index.md"
        label: "Grooming"
        name: "grooming"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "SEO",
              name: seo,
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: string },
                  { label: "Description", name: "description", widget: "text" },
                  {
                    label: "Featured Image",
                    name: "featured_image",
                    widget: image,
                  },
                ],
            }
          - {
              label: "Services Intro",
              name: services_intro,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Copy", name: "copy", widget: "text" },
                  {
                    label: "Service List",
                    name: "service_list",
                    widget: "list",
                    fields:
                      [{ label: "Service", name: "service", widget: string }],
                  },
                  {
                    label: "Closing Copy",
                    name: "closing_copy",
                    widget: "text",
                  },
                ],
            }
      - file: "content/services/emergency-services/index.md"
        label: "Emergency Services"
        name: "emergency-services"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "SEO",
              name: seo,
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: string },
                  { label: "Description", name: "description", widget: "text" },
                  {
                    label: "Featured Image",
                    name: "featured_image",
                    widget: image,
                  },
                ],
            }
          - {
              label: "Services Intro",
              name: services_intro,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Copy", name: "copy", widget: "text" },
                  {
                    label: "Service List",
                    name: "service_list",
                    widget: "list",
                    fields:
                      [{ label: "Service", name: "service", widget: string }],
                  },
                ],
            }
      - file: "content/careers/_index.md"
        label: "Careers"
        name: "careers"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "SEO",
              name: seo,
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: string },
                  { label: "Description", name: "description", widget: "text" },
                  {
                    label: "Featured Image",
                    name: "featured_image",
                    widget: image,
                  },
                ],
            }
      - file: "content/about/_index.md"
        label: "About"
        name: "about"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "SEO",
              name: seo,
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: string },
                  { label: "Description", name: "description", widget: "text" },
                  {
                    label: "Featured Image",
                    name: "featured_image",
                    widget: image,
                  },
                ],
            }
          - {
              label: "Intro",
              name: intro,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Copy", name: "copy", widget: "text" },
                ],
            }
          - {
              label: "Leadership",
              name: leadership,
              widget: object,
              fields: [{ label: "Heading", name: "heading", widget: string }],
            }
          - {
              label: "Team",
              name: "team",
              widget: "list",
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Title", name: "title", widget: string },
                  { label: Headshot, name: headshot, widget: image },
                  { label: "Copy", name: "copy", widget: "text" },
                ],
            }
      - file: "content/contact/_index.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "SEO",
              name: seo,
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: string },
                  { label: "Description", name: "description", widget: "text" },
                  {
                    label: "Featured Image",
                    name: "featured_image",
                    widget: image,
                  },
                ],
            }
